version: '2'

services:
  mongodb:
    container_name: whitestation_db
    hostname: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    mem_limit: 2g  # Exemple: Limite la mémoire à 2 Go

    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
    driver: local
