version: '2'

services:
  mongodb:
    container_name: whitestation_db
    hostname: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3