version: '3'

services:
  mongodb:
    container_name: whitestation_db
    hostname: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    mem_limit: 2g

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
