version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-instance
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
